"use client"

import { FormEvent, useEffect, useMemo, useRef, useState } from "react"
import { Markdown } from "../../components/markdown"

const api = process.env.NEXT_PUBLIC_API_URL || "/api"
type Status = "draft" | "hidden" | "published"
type Post = { id?: number; title: string; slug: string; excerpt: string; content: string; tags: string[]; status: Status; publishedAt: string | null }
type Project = { id?: number; title: string; slug: string; description: string; tags: string[]; url: string; status: Status }
type Link = { label: string; url: string }
type Site = { displayName: string; handle: string; avatarUrl: string; homeIntro: string; aboutTitle: string; aboutContent: string; links: Link[] }
const blankPost = (): Post => ({ title: "", slug: "", excerpt: "", content: "", tags: [], status: "draft", publishedAt: null })
const blankProject = (): Project => ({ title: "", slug: "", description: "", tags: [], url: "", status: "draft" })
const blankSite: Site = { displayName: "", handle: "", avatarUrl: "", homeIntro: "", aboutTitle: "", aboutContent: "", links: [] }
const statusText: Record<Status, string> = { draft: "草稿", hidden: "隐藏", published: "已发布" }
const toLocalTime = (date: string | null) => date ? new Date(new Date(date).getTime() - new Date(date).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ""
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

export default function Admin() {
  const [token, setToken] = useState(""), [password, setPassword] = useState(""), [section, setSection] = useState<"posts" | "projects" | "site">("posts"), [mode, setMode] = useState<"list" | "edit">("list")
  const [posts, setPosts] = useState<Post[]>([]), [projects, setProjects] = useState<Project[]>([]), [site, setSite] = useState<Site>(blankSite), [post, setPost] = useState<Post>(blankPost), [project, setProject] = useState<Project>(blankProject)
  const [preview, setPreview] = useState(false), [loading, setLoading] = useState(false), [notice, setNotice] = useState("")

  const request = async (path: string, init: RequestInit = {}) => fetch(`${api}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, ...(init.headers || {}) } })
  const load = async (accessToken = token) => {
    if (!accessToken) return
    setLoading(true)
    const headers = { Authorization: `Bearer ${accessToken}` }
    const [postsResponse, projectsResponse, siteResponse] = await Promise.all([fetch(`${api}/admin/posts`, { headers }), fetch(`${api}/admin/projects`, { headers }), fetch(`${api}/admin/site`, { headers })])
    if (postsResponse.status === 401) { sessionStorage.removeItem("blog-admin-token"); setToken(""); setNotice("登录已过期，请重新登录。"); setLoading(false); return }
    if (postsResponse.ok) setPosts(await postsResponse.json())
    if (projectsResponse.ok) setProjects(await projectsResponse.json())
    if (siteResponse.ok) { const nextSite = await siteResponse.json(); setSite({ ...blankSite, ...nextSite, links: Array.isArray(nextSite.links) ? nextSite.links : [] }) }
    setLoading(false)
  }
  useEffect(() => { const saved = sessionStorage.getItem("blog-admin-token"); if (saved) { setToken(saved); void load(saved) } }, [])
  const stats = useMemo(() => ({ posts: posts.length, projects: projects.length, published: posts.filter((item) => item.status === "published").length }), [posts, projects])

  const login = async (event: FormEvent) => { event.preventDefault(); setNotice(""); const response = await fetch(`${api}/admin/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); if (!response.ok) return setNotice("密码不正确，请重试。"); const data = await response.json(); sessionStorage.setItem("blog-admin-token", data.token); setToken(data.token); setPassword(""); void load(data.token) }
  const savePost = async (event: FormEvent) => { event.preventDefault(); if (!post.title || !post.slug) return setNotice("文章需要标题和 slug。"); const payload = post.status === "published" && !post.publishedAt ? { ...post, publishedAt: new Date().toISOString() } : post; setLoading(true); const response = await request(`/admin/posts${post.id ? `/${post.id}` : ""}`, { method: post.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setLoading(false); if (!response.ok) return setNotice("保存失败，请检查 slug 是否唯一且仅含英文、数字、连字符。"); setNotice(payload.status === "published" ? "文章已发布。" : "草稿已保存。"); setMode("list"); await load() }
  const saveProject = async (event: FormEvent) => { event.preventDefault(); if (!project.title || !project.slug) return setNotice("项目需要名称和 slug。"); setLoading(true); const response = await request(`/admin/projects${project.id ? `/${project.id}` : ""}`, { method: project.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(project) }); setLoading(false); if (!response.ok) return setNotice("项目保存失败，请检查链接和 slug。"); setNotice(project.status === "published" ? "项目已发布。" : "项目草稿已保存。"); setMode("list"); await load() }
  const saveSite = async (event: FormEvent) => { event.preventDefault(); setLoading(true); const response = await request("/admin/site", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(site) }); setLoading(false); if (!response.ok) return setNotice("站点资料保存失败，请检查头像和链接地址。"); setNotice("站点资料已保存，前台刷新后即可看到更新。"); await load() }
  const uploadAvatar = async (file: File) => { const body = new FormData(); body.append("file", file); const response = await request("/admin/uploads/avatar", { method: "POST", body }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.message || "头像上传失败。"); return result.url as string }
  const remove = async (kind: "posts" | "projects", item: Post | Project) => { if (!item.id || !window.confirm(`确定删除《${item.title}》吗？`)) return; setLoading(true); const response = await request(`/admin/${kind}/${item.id}`, { method: "DELETE" }); setLoading(false); if (!response.ok) return setNotice("删除失败，请稍后重试。"); setNotice("已删除。"); await load() }
  const logout = () => { sessionStorage.removeItem("blog-admin-token"); setToken(""); setNotice("") }

  if (!token) return <main className="admin login-page"><form className="login" onSubmit={login}><span className="eyebrow">MICHIKATSU / ADMIN</span><h1>内容管理</h1><p>统一管理个人资料、页面内容、项目与文章。</p><label>管理密码<input type="password" autoFocus placeholder="输入密码" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button>进入后台</button>{notice && <p className="notice error">{notice}</p>}</form></main>

  return <main className="admin">
    <header className="admin-header"><div><span className="eyebrow">MICHIKATSU / CONTENT</span><h1>站点管理</h1></div><div className="header-actions"><a href="/" target="_blank" rel="noreferrer">查看网站 ↗</a><button className="text-button" onClick={logout}>退出</button></div></header>
    <nav className="admin-nav"><button className={section === "posts" ? "active" : ""} onClick={() => { setSection("posts"); setMode("list") }}>文章 <span>{stats.posts}</span></button><button className={section === "projects" ? "active" : ""} onClick={() => { setSection("projects"); setMode("list") }}>项目 <span>{stats.projects}</span></button><button className={section === "site" ? "active" : ""} onClick={() => { setSection("site"); setMode("list") }}>站点资料</button></nav>
    {notice && <div className="notice">{notice}<button className="dismiss" onClick={() => setNotice("")}>×</button></div>}
    {section === "posts" && (mode === "list" ? <List title="文章" hint="发布的文章会显示在首页和 Blog 页面。" count={stats.published} countLabel="已发布" loading={loading} empty="还没有文章，从第一篇开始吧。" create={() => { setPost(blankPost()); setPreview(false); setMode("edit") }} items={posts} edit={(item) => { setPost(item as Post); setPreview(false); setMode("edit") }} remove={(item) => remove("posts", item)} /> : <PostEditor post={post} setPost={setPost} preview={preview} setPreview={setPreview} back={() => setMode("list")} save={savePost} loading={loading} />)}
    {section === "projects" && (mode === "list" ? <List title="项目" hint="项目可以附带官网、仓库或作品链接。" count={projects.filter((item) => item.status === "published").length} countLabel="已发布" loading={loading} empty="还没有项目，添加一个作品吧。" create={() => { setProject(blankProject()); setMode("edit") }} items={projects} edit={(item) => { setProject(item as Project); setMode("edit") }} remove={(item) => remove("projects", item)} /> : <ProjectEditor project={project} setProject={setProject} back={() => setMode("list")} save={saveProject} loading={loading} />)}
    {section === "site" && <SiteEditor site={site} setSite={setSite} save={saveSite} upload={uploadAvatar} loading={loading} />}
  </main>
}

function List({ title, hint, count, countLabel, loading, empty, create, items, edit, remove }: { title: string; hint: string; count: number; countLabel: string; loading: boolean; empty: string; create: () => void; items: (Post | Project)[]; edit: (item: Post | Project) => void; remove: (item: Post | Project) => void }) { return <><section className="metrics"><div><span>全部{title}</span><strong>{items.length}</strong></div><div><span>{countLabel}</span><strong>{count}</strong></div><div><span>草稿</span><strong>{items.filter((item) => item.status === "draft").length}</strong></div></section><section className="post-panel"><div className="panel-heading"><div><h2>{title}管理</h2><p>{hint}</p></div><button onClick={create}>+ 新建{title.slice(0, -1) || title}</button></div>{loading ? <div className="empty-admin">正在加载…</div> : items.length ? <div className="post-table"><div className="table-head"><span>名称</span><span>状态</span><span>地址</span><span>操作</span></div>{items.map((item) => <article className="post-row" key={item.id}><div><button className="post-title" onClick={() => edit(item)}>{item.title || "未命名"}</button><p>/{item.slug} · {"excerpt" in item ? item.excerpt || "暂无摘要" : item.description || "暂无描述"}</p></div><span className={`status ${item.status}`}>{statusText[item.status]}</span><span className="row-meta">{"url" in item && item.url ? "已设置链接" : "—"}</span><div className="row-actions"><button className="text-button" onClick={() => edit(item)}>编辑</button><button className="danger-button" onClick={() => remove(item)}>删除</button></div></article>)}</div> : <div className="empty-admin"><div className="empty-icon">✦</div><h3>{empty}</h3><button onClick={create}>立即新建</button></div>}</section></> }

function PostEditor({ post, setPost, preview, setPreview, back, save, loading }: { post: Post; setPost: (post: Post) => void; preview: boolean; setPreview: (value: boolean) => void; back: () => void; save: (event: FormEvent) => void; loading: boolean }) {
  const contentRef = useRef<HTMLTextAreaElement>(null)
  const words = post.content.trim() ? post.content.trim().split(/\s+/).length : 0
  const insert = (before: string, after = "", fallback = "文字") => { const field = contentRef.current; const start = field?.selectionStart ?? post.content.length; const end = field?.selectionEnd ?? start; const selected = post.content.slice(start, end) || fallback; const next = `${post.content.slice(0, start)}${before}${selected}${after}${post.content.slice(end)}`; setPost({ ...post, content: next }); requestAnimationFrame(() => { field?.focus(); field?.setSelectionRange(start + before.length, start + before.length + selected.length) }) }
  return <section className="editor-shell"><div className="writer-header"><button className="back-button" onClick={back}>← 所有文章</button><div><span className={`writer-status ${post.status}`}>{statusText[post.status]}</span><span className="writer-count">{words} 词 · 预计 {Math.max(1, Math.ceil(words / 250))} 分钟阅读</span></div></div><form className="editor writer-layout" onSubmit={save}><div className="editor-main writer-canvas"><input className="title-input" placeholder="给文章起一个标题" value={post.title} onChange={(event) => setPost({ ...post, title: event.target.value, slug: post.slug || slugify(event.target.value) })} /><div className="slug-field"><span>blog.michikatsu.top/posts/</span><input placeholder="article-slug" value={post.slug} onChange={(event) => setPost({ ...post, slug: slugify(event.target.value) })} /></div><textarea className="excerpt-input" placeholder="摘要：一句话告诉读者这篇文章讲什么（可选）" value={post.excerpt} onChange={(event) => setPost({ ...post, excerpt: event.target.value })} /><div className="content-header"><span>正文</span><button type="button" className="preview-button" onClick={() => setPreview(!preview)}>{preview ? "返回编辑" : "阅读预览"}</button></div>{preview ? <div className="markdown-preview"><Markdown content={post.content || "# 预览\n\n开始写作后，内容会显示在这里。"} /></div> : <><div className="markdown-toolbar"><button type="button" onClick={() => insert("# ", "", "标题")}>H1</button><button type="button" onClick={() => insert("## ", "", "小标题")}>H2</button><button type="button" onClick={() => insert("**", "**", "加粗文字")}>B</button><button type="button" onClick={() => insert("*", "*", "强调文字")}>I</button><button type="button" onClick={() => insert("[", "](https://)", "链接文字")}>链接</button><button type="button" onClick={() => insert("> ", "", "引用")}>引用</button><button type="button" onClick={() => insert("`", "`", "代码")}>代码</button><button type="button" onClick={() => insert("![图片说明](", ")", "https://")}>图片</button></div><textarea ref={contentRef} className="content writer-content" placeholder="从这里开始写作…\n\n支持 Markdown；工具栏可快速插入标题、链接、引用、代码与图片。" value={post.content} onChange={(event) => setPost({ ...post, content: event.target.value })} /></>}</div><PublishPanel status={post.status} setStatus={(status) => setPost({ ...post, status })} tags={post.tags} setTags={(tags) => setPost({ ...post, tags })} date={post.publishedAt} setDate={(publishedAt) => setPost({ ...post, publishedAt })} loading={loading} /></form></section>
}

function ProjectEditor({ project, setProject, back, save, loading }: { project: Project; setProject: (project: Project) => void; back: () => void; save: (event: FormEvent) => void; loading: boolean }) { return <section className="editor-shell"><div className="editor-top"><button className="back-button" onClick={back}>← 返回项目列表</button><span>{project.id ? "编辑项目" : "新建项目"}</span></div><form className="editor" onSubmit={save}><div className="editor-main"><input className="title-input" placeholder="项目名称" value={project.title} onChange={(event) => setProject({ ...project, title: event.target.value, slug: project.slug || slugify(event.target.value) })} /><div className="slug-field"><span>项目标识 /</span><input placeholder="project-slug" value={project.slug} onChange={(event) => setProject({ ...project, slug: slugify(event.target.value) })} /></div><textarea className="content project-description" placeholder="用几句话介绍这个项目" value={project.description} onChange={(event) => setProject({ ...project, description: event.target.value })} /><label className="plain-label">项目链接<input placeholder="https://github.com/..." value={project.url} onChange={(event) => setProject({ ...project, url: event.target.value })} /></label></div><PublishPanel status={project.status} setStatus={(status) => setProject({ ...project, status })} tags={project.tags} setTags={(tags) => setProject({ ...project, tags })} loading={loading} /></form></section> }

function PublishPanel({ status, setStatus, tags, setTags, date, setDate, loading }: { status: Status; setStatus: (status: Status) => void; tags: string[]; setTags: (tags: string[]) => void; date?: string | null; setDate?: (date: string | null) => void; loading: boolean }) { return <aside className="publish-panel"><h2>发布设置</h2><label>状态<select value={status} onChange={(event) => setStatus(event.target.value as Status)}><option value="draft">草稿</option><option value="published">发布</option><option value="hidden">隐藏</option></select></label>{setDate && <label>发布时间<input type="datetime-local" value={toLocalTime(date || null)} onChange={(event) => setDate(event.target.value ? new Date(event.target.value).toISOString() : null)} /></label>}<label>标签<input placeholder="例如：设计, 技术" value={tags.join(", ")} onChange={(event) => setTags(event.target.value.split(",").map((item) => item.trim()).filter(Boolean))} /></label><button disabled={loading}>{loading ? "正在保存…" : status === "published" ? "发布" : "保存草稿"}</button></aside> }

function SiteEditor({ site, setSite, save, upload, loading }: { site: Site; setSite: (site: Site) => void; save: (event: FormEvent) => void; upload: (file: File) => Promise<string>; loading: boolean }) {
  const input = useRef<HTMLInputElement>(null)
  const [source, setSource] = useState("")
  const [zoom, setZoom] = useState(1)
  const [rotation, setRotation] = useState(0)
  const [offset, setOffset] = useState({ x: 0, y: 0 })
  const drag = useRef<{ pointerId: number; x: number; y: number; originX: number; originY: number } | null>(null)
  const [avatarNotice, setAvatarNotice] = useState("")
  const updateLink = (index: number, field: keyof Link, value: string) => setSite({ ...site, links: site.links.map((link, current) => current === index ? { ...link, [field]: value } : link) })
  const chooseAvatar = (file?: File) => { if (!file) return; if (!file.type.startsWith("image/") || file.size > 5 * 1024 * 1024) return setAvatarNotice("请选择不超过 5MB 的 JPG、PNG 或 WebP 图片。"); setSource(URL.createObjectURL(file)); setZoom(1); setRotation(0); setOffset({ x: 0, y: 0 }); setAvatarNotice("") }
  const startDrag = (event: React.PointerEvent<HTMLDivElement>) => { if (!source) return; event.currentTarget.setPointerCapture(event.pointerId); drag.current = { pointerId: event.pointerId, x: event.clientX, y: event.clientY, originX: offset.x, originY: offset.y } }
  const moveDrag = (event: React.PointerEvent<HTMLDivElement>) => { const active = drag.current; if (!active || active.pointerId !== event.pointerId) return; setOffset({ x: Math.max(-120, Math.min(120, active.originX + event.clientX - active.x)), y: Math.max(-120, Math.min(120, active.originY + event.clientY - active.y)) }) }
  const endDrag = (event: React.PointerEvent<HTMLDivElement>) => { if (drag.current?.pointerId === event.pointerId) drag.current = null }
  const saveAvatar = async () => {
    if (!source) return
    setAvatarNotice("正在处理头像…")
    const image = new Image(); image.src = source
    await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error("图片读取失败。")) })
    const canvas = document.createElement("canvas"); canvas.width = canvas.height = 512
    const context = canvas.getContext("2d"); if (!context) return
    context.fillStyle = "#202121"; context.fillRect(0, 0, 512, 512)
    const scale = Math.max(512 / image.naturalWidth, 512 / image.naturalHeight) * zoom
    context.translate(256 + offset.x * 4, 256 + offset.y * 4); context.rotate(rotation * Math.PI / 180); context.scale(scale, scale); context.drawImage(image, -image.naturalWidth / 2, -image.naturalHeight / 2)
    const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/webp", 0.9))
    if (!blob) return setAvatarNotice("头像处理失败，请重试。")
    try { const url = await upload(new File([blob], "avatar.webp", { type: "image/webp" })); setSite({ ...site, avatarUrl: url }); setSource(""); setAvatarNotice("头像已上传，请点击“保存资料”应用到前台。") } catch (error) { setAvatarNotice(error instanceof Error ? error.message : "头像上传失败。") }
  }
  return <form className="site-editor" onSubmit={save}>
    <section className="post-panel"><div className="panel-heading"><div><h2>个人资料与首页</h2><p>控制侧边栏头像、名称、账号和首页介绍。</p></div><button disabled={loading}>保存资料</button></div><div className="form-grid"><label>显示名称<input value={site.displayName} placeholder="例如：Michikatsu" onChange={(event) => setSite({ ...site, displayName: event.target.value })} /></label><label>账号（不含 @）<input value={site.handle} placeholder="yourhandle" onChange={(event) => setSite({ ...site, handle: event.target.value.replace(/^@/, "") })} /></label><div className="avatar-manager full"><div className={`avatar-preview ${source ? "draggable" : ""}`} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}>{source || site.avatarUrl ? <img src={source || site.avatarUrl} alt="头像预览" style={source ? { transform: `translate(${offset.x}px, ${offset.y}px) scale(${zoom}) rotate(${rotation}deg)` } : undefined} /> : <span>{site.displayName.slice(0, 1).toUpperCase() || "?"}</span>}</div><div className="avatar-controls"><div><b>头像</b><p>{source ? "直接拖动图片调整构图；也可缩放、旋转。" : "上传后可缩放、旋转并拖动裁切为方形头像。"}</p></div><input ref={input} className="file-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => chooseAvatar(event.target.files?.[0])} /><button type="button" className="secondary-button" onClick={() => input.current?.click()}>选择图片</button></div>{source && <div className="crop-controls"><label>缩放<input type="range" min="1" max="2.8" step="0.01" value={zoom} onChange={(event) => setZoom(Number(event.target.value))} /></label><label>旋转<input type="range" min="-180" max="180" step="1" value={rotation} onChange={(event) => setRotation(Number(event.target.value))} /></label><button type="button" onClick={saveAvatar}>保存裁切后的头像</button></div>}{avatarNotice && <p className="avatar-notice">{avatarNotice}</p>}</div><label className="full">首页简介<textarea value={site.homeIntro} placeholder="写一句欢迎语或个人定位" onChange={(event) => setSite({ ...site, homeIntro: event.target.value })} /></label></div></section>
    <section className="post-panel"><div className="panel-heading"><div><h2>个人链接</h2><p>例如 GitHub、邮箱、X、Bilibili 或作品集。</p></div><button type="button" className="text-button" onClick={() => setSite({ ...site, links: [...site.links, { label: "", url: "" }] })}>+ 添加链接</button></div><div className="link-list">{site.links.length ? site.links.map((link, index) => <div className="link-row" key={index}><input placeholder="链接名称" value={link.label} onChange={(event) => updateLink(index, "label", event.target.value)} /><input placeholder="https://..." value={link.url} onChange={(event) => updateLink(index, "url", event.target.value)} /><button type="button" className="danger-button" onClick={() => setSite({ ...site, links: site.links.filter((_, current) => current !== index) })}>删除</button></div>) : <p className="muted">还没有链接。</p>}</div></section>
    <section className="post-panel"><div className="panel-heading"><div><h2>About 页面</h2><p>支持 Markdown，用于完整个人介绍。</p></div></div><div className="form-grid"><label className="full">页面标题<input value={site.aboutTitle} placeholder="About" onChange={(event) => setSite({ ...site, aboutTitle: event.target.value })} /></label><label className="full">介绍内容<textarea className="about-editor" value={site.aboutContent} placeholder="# 你好\n\n介绍你自己、经历和正在做的事。" onChange={(event) => setSite({ ...site, aboutContent: event.target.value })} /></label></div><button disabled={loading}>{loading ? "正在保存…" : "保存所有站点资料"}</button></section>
  </form>
}
