import type { Metadata } from "next"
import "./globals.css"
import "./functional.css"
import "./categories.css"
import "./sidebar-compact.css"
import "./sidebar-clean.css"
import "./markdown.css"
import "./code.css"
import "./reader.css"
import "./feed.css"
import "./about.css"
import "./about-resume.css"
import "./resume.css"
import "./empty-state.css"
import "./admin/admin.css"
import "./admin/admin-layout.css"
import "./admin/avatar.css"
import "./admin/avatar-drag.css"
import "./admin/writer.css"
import "./admin/preview.css"
import "./admin/pins.css"
import "./mobile.css"
import "./responsive-fixes.css"
import "./desktop-layout.css"
import "./project-detail.css"
import "./about-editor.css"
import "./admin/project-editor.css"
import "./admin/resume-editor.css"
export const metadata: Metadata = { title: "Michikatsu｜个人网站", description: "Michikatsu 的文章、项目与个人介绍" }
export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="zh-CN"><body>{children}</body></html> }
