"use client"

import { CSSProperties, useState } from "react"

const profile = { name: "Your Name", handle: "@yourhandle", avatarUrl: "", photoUrl: "", initials: "YN", stats: [{ value: "7", label: "Posts" }, { value: "3", label: "Projects" }], links: [{ label: "GitHub", href: "https://github.com/yourhandle" }, { label: "Email", href: "mailto:hello@example.com" }, { label: "X / Twitter", href: "https://x.com/yourhandle" }] }
const projects = [{ title: "Paperlane Blog", description: "A personal publishing space for independent creators.", tags: ["Next.js", "Hono", "Tailwind"], kind: "editor", featured: true }, { title: "Flow Canvas", description: "A visual workspace for making complex team processes clear.", tags: ["React", "Zustand", "react-flow"], kind: "canvas", featured: true }, { title: "Care System", description: "A reliable operational console for professional teams.", tags: ["Vue", "Pinia"], kind: "system", featured: true }, { title: "Shore Camp", description: "A calm, immersive brand site built with Next.js.", tags: ["Next.js", "Motion"], kind: "shore", featured: false }]
const pages: Record<string, [string, string]> = { Home: ["Home", "Hi, I am Your Name. I design and build thoughtful experiences for the web."], About: ["About", "A short introduction, your experience and the things you care about."], Blog: ["Blog", "Notes on design, development and a life spent on the web."] }
export default function Home() {
  const [light, setLight] = useState(false), [view, setView] = useState("Projects"), [settings, setSettings] = useState(false), [radius, setRadius] = useState(22), [serif, setSerif] = useState(false), [shadow, setShadow] = useState(true), [accent, setAccent] = useState("#9bf443")
  const style = { "--radius": `${radius}px`, "--accent": accent } as CSSProperties
  return <div className={`site soft ${light ? "light" : ""} ${serif ? "serif" : ""} ${shadow ? "soft-shadow" : ""}`} style={style}>
    <aside><section className="profile-card"><div className="profile-avatar" style={profile.avatarUrl ? { backgroundImage: `url(${profile.avatarUrl})` } : undefined}>{profile.avatarUrl ? null : profile.initials}</div><h1>{profile.name}</h1><p>{profile.handle}</p><div className="profile-stats">{profile.stats.map(s => <div key={s.label}><b>{s.value}</b><span>{s.label}</span></div>)}</div><div className="profile-links">{profile.links.map(l => <a key={l.label} href={l.href} target={l.href.startsWith("http") ? "_blank" : undefined} rel="noreferrer">{l.label}<span>↗</span></a>)}</div></section><nav className="primary-nav">{["Home", "About", "Projects", "Blog"].map(x => <button className={view === x ? "selected" : ""} onClick={() => setView(x)} key={x}><i>{x === "Home" ? "⌂" : x === "About" ? "♙" : x === "Projects" ? "▣" : "◔"}</i>{x}</button>)}</nav><div className="side-footer">© 2026 · your personal space</div></aside>
    <main>{view === "Projects" ? <Projects /> : view === "Blog" ? <Blog /> : view === "About" ? <About /> : <Page view={view} />}</main>
    <button className="settings-trigger" onClick={() => setSettings(!settings)} aria-label="Open appearance settings">⚙</button>
    {settings && <section className="settings-panel"><button className="close-settings" onClick={() => setSettings(false)}>×</button><h3>Appearance</h3><label className="setting-line">Night mode <button className="switch" onClick={() => setLight(!light)}><i className={light ? "on" : ""}/></button></label><label className="setting-line">Typeface <span className="segmented"><button className={!serif ? "active" : ""} onClick={() => setSerif(false)}>Sans</button><button className={serif ? "active" : ""} onClick={() => setSerif(true)}>Serif</button></span></label><label className="setting-line">Shadow <button className="switch" onClick={() => setShadow(!shadow)}><i className={shadow ? "on" : ""}/></button></label><label className="setting-line color-line">Accent <span>{["#9bf443", "#4bb8ff", "#e4a2d5", "#d7a36b"].map(c => <button aria-label={`Use ${c}`} className={accent === c ? "chosen" : ""} style={{ background: c }} onClick={() => setAccent(c)} key={c}/>)}</span></label><label className="radius-label">Roundness <input type="range" min="12" max="40" value={radius} onChange={e => setRadius(Number(e.target.value))}/></label></section>}
  </div>
}
function Projects() { return <><section className="title"><h2>Projects</h2><p>Several projects that I have worked on, both private and open source.</p></section><section className="grid">{projects.map((p, i) => <article className="card" key={p.title}><div className={`preview ${p.kind}`}>{p.featured && <span className="badge">✦ Featured</span>}<div className="screen"><div className="browser"><i/><i/><i/></div><div className="screen-content"><b>{String(i + 1).padStart(2, "0")}</b><span/><span/><span/></div></div><button className="view-project">View Project</button></div><div className="card-body"><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div></div></article>)}</section></> }
function Blog() { const [topic, setTopic] = useState("All posts"); const topics = ["All posts", "Design", "Development", "Notes", "Life"]; const posts = ["Designing for calm", "Shipping small tools", "Why I still believe in the web"]; return <><section className="title"><h2>Blog</h2><p>Notes on design, development and a life spent on the web.</p></section><section className="blog-categories"><span>Browse by topic</span><div>{topics.map(item => <button className={topic === item ? "active" : ""} onClick={() => setTopic(item)} key={item}>{item}</button>)}</div></section><div className="list">{posts.map((x, i) => <button className="list-row" key={x}><span>0{i + 1}</span><strong>{x}</strong><b>↗</b></button>)}</div></> }
function About(){const skills=["TypeScript","React","Next.js","Hono","Node.js","PostgreSQL","Docker","Nginx","Figma","Git"];return <article className="about-page"><div className="about-photo" style={profile.photoUrl?{backgroundImage:`url(${profile.photoUrl})`}:undefined}>{profile.photoUrl?null:<span>Photo<br/>goes here</span>}</div><div className="about-copy"><p className="about-kicker">ABOUT ME</p><h2>Hi, I&apos;m {profile.name}.</h2><p>I am an independent developer and designer who cares about thoughtful, long-lasting experiences on the web.</p><div className="about-notes"><span>Based in Shanghai / Remote</span><span>Available for selected projects</span></div></div><section className="about-section skills"><h3>⌘ Skills</h3><p>My professional toolkit.</p><div>{skills.map(skill=><span key={skill}>{skill}</span>)}</div></section><section className="about-section"><h3>▱ Education</h3><p>My educational journey.</p><article className="resume-card"><b>University / School Name</b><span>Bachelor&apos;s degree · Major</span><small>2018 — 2022</small></article></section><section className="about-section"><h3>◌ Experience</h3><p>Selected work experience.</p><div className="experience"><article><span>2023 — Now</span><div><b>Product Engineer · Your Company</b><p>Designing and building reliable web products from concept to launch.</p></div></article><article><span>2021 — 2023</span><div><b>Frontend Developer · Previous Company</b><p>Worked with cross-functional teams to deliver polished interfaces.</p></div></article></div></section></article>}
function Page({ view }: { view: string }) { const [title, intro] = pages[view]; const list = ["Background", "What I do", "How to reach me"]; return <><section className="title"><h2>{title}</h2><p>{intro}</p></section><div className="list">{list.map((x, i) => <button className="list-row" key={x}><span>0{i + 1}</span><strong>{x}</strong><b>↗</b></button>)}</div></> }
